### ISSUE TITLE
Note for Leapmotion plugin compatibility

### ISSUE THREAD

**Issue by lualucky** [BluePengcho/Open_Source_Hand_Tracking_Live2D_Model#1]
Model is really cool! Just one note about how the leapmotion plugin calculates parameters, if you disagree with this paradigm please let me know, it's all still in the works.
For Extend/Extension
    1 is the default: fully extended/longest
    0 is the shortest

Other than that I'm realizing a lot of problems with my plugin, so it's already working! lol

**Comment by BluePengcho** [comment]
I've changed and updated the Extension parameters to match the Leapmotion plugin parameters (1-0), your writing the book for Live2D hand tracking so trying to match your method and parameters to standardise is a great idea to me.

Glad its already been found useful, any other changes or extra features that could be helpful let me know (^v^)b
